import { z } from 'zod';
import { adminProcedure, router, superAdminProcedure } from '../_core/trpc';
import { TRPCError } from '@trpc/server';
import { getDb } from '../db';

export const franchiseePaymentRouter = router({

  listPayments: adminProcedure
    .input(z.object({
      userId: z.number().optional(),
      year: z.number(),
      month: z.number(),
    }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: '資料庫連線失敗' });

      const { year, month, userId } = input;
      const params: any[] = [year, month];
      let whereParts = `YEAR(p.paymentDate)=? AND MONTH(p.paymentDate)=?`;
      if (userId) {
        whereParts += ' AND p.userId=?';
        params.push(userId);
      }

      const [rows] = await (db as any).$client.execute(
        `SELECT p.*, u.name AS userName
         FROM os_franchisee_payments p
         LEFT JOIN users u ON u.id = p.userId
         WHERE ${whereParts}
         ORDER BY p.paymentDate DESC, p.id DESC`,
        params
      );
      const payments = rows as any[];

      // summary
      let totalReceivable = 0;
      let totalPaid = 0;
      const byFranchiseeMap: Record<number, { userId: number; name: string; receivable: number; paid: number }> = {};

      for (const p of payments) {
        const amt = Number(p.amount);
        if (p.direction === 'receivable') totalReceivable += amt;
        else totalPaid += amt;

        const uid = p.userId;
        if (!byFranchiseeMap[uid]) {
          byFranchiseeMap[uid] = { userId: uid, name: p.userName ?? `ID:${uid}`, receivable: 0, paid: 0 };
        }
        if (p.direction === 'receivable') byFranchiseeMap[uid].receivable += amt;
        else byFranchiseeMap[uid].paid += amt;
      }

      const byFranchisee = Object.values(byFranchiseeMap).map(f => ({
        ...f,
        outstanding: f.receivable - f.paid,
      }));

      return {
        payments,
        summary: {
          totalReceivable,
          totalPaid,
          outstanding: totalReceivable - totalPaid,
        },
        byFranchisee,
      };
    }),

  createPayment: superAdminProcedure
    .input(z.object({
      userId: z.number(),
      paymentDate: z.string(),
      amount: z.number(),
      direction: z.enum(['receivable', 'paid']),
      category: z.string().default('貨款'),
      note: z.string().optional(),
      paidAt: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: '資料庫連線失敗' });

      const createdBy = ctx.user.name ?? ctx.user.email ?? 'admin';
      const [result] = await (db as any).$client.execute(
        `INSERT INTO os_franchisee_payments
           (tenantId, userId, paymentDate, amount, direction, category, note, createdBy, paidAt)
         VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          input.userId,
          input.paymentDate,
          input.amount,
          input.direction,
          input.category,
          input.note ?? null,
          createdBy,
          input.paidAt ?? null,
        ]
      );
      return { id: (result as any).insertId };
    }),

  markPaid: superAdminProcedure
    .input(z.object({
      receivableId: z.number(),
      paidAmount: z.number(),
      paidAt: z.string(),
      note: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: '資料庫連線失敗' });

      // 查原記錄
      const [origRows] = await (db as any).$client.execute(
        `SELECT * FROM os_franchisee_payments WHERE id=? AND direction='receivable'`,
        [input.receivableId]
      );
      const orig = (origRows as any[])[0];
      if (!orig) throw new TRPCError({ code: 'NOT_FOUND', message: '找不到應收記錄' });

      const createdBy = ctx.user.name ?? ctx.user.email ?? 'admin';

      // 新增一筆已收
      const [result] = await (db as any).$client.execute(
        `INSERT INTO os_franchisee_payments
           (tenantId, userId, paymentDate, amount, direction, category, note, createdBy, paidAt, isAutoGenerated)
         VALUES (1, ?, ?, ?, 'paid', ?, ?, ?, ?, 1)`,
        [
          orig.userId,
          input.paidAt,
          input.paidAmount,
          orig.category,
          input.note ?? null,
          createdBy,
          input.paidAt,
        ]
      );

      // 更新原應收備註
      const appendNote = `已於 ${input.paidAt} 收款 ${input.paidAmount}`;
      const newNote = orig.note ? `${orig.note}；${appendNote}` : appendNote;
      await (db as any).$client.execute(
        `UPDATE os_franchisee_payments SET note=?, paidAt=? WHERE id=?`,
        [newNote, input.paidAt, input.receivableId]
      );

      return { id: (result as any).insertId };
    }),

  exportPayments: adminProcedure
    .input(z.object({
      userId: z.number().optional(),
      year: z.number(),
      month: z.number(),
    }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: '資料庫連線失敗' });

      const { year, month, userId } = input;
      const params: any[] = [year, month];
      let whereParts = `YEAR(p.paymentDate)=? AND MONTH(p.paymentDate)=?`;
      if (userId) {
        whereParts += ' AND p.userId=?';
        params.push(userId);
      }

      const [rows] = await (db as any).$client.execute(
        `SELECT p.paymentDate, u.name AS userName, p.category, p.amount, p.direction, p.note
         FROM os_franchisee_payments p
         LEFT JOIN users u ON u.id = p.userId
         WHERE ${whereParts}
         ORDER BY p.paymentDate ASC, u.name ASC`,
        params
      );
      const payments = rows as any[];

      let totalReceivable = 0;
      let totalPaid = 0;
      for (const p of payments) {
        if (p.direction === 'receivable') totalReceivable += Number(p.amount);
        else totalPaid += Number(p.amount);
      }

      const headers = ['日期', '加盟主', '類別', '金額', '方向', '備註'];
      const dataRows = payments.map(p => [
        p.paymentDate instanceof Date
          ? p.paymentDate.toISOString().slice(0, 10)
          : String(p.paymentDate).slice(0, 10),
        p.userName ?? '',
        p.category ?? '',
        Number(p.amount),
        p.direction === 'receivable' ? '應收' : '已付',
        p.note ?? '',
      ]);

      return {
        headers,
        rows: dataRows,
        summary: {
          year,
          month,
          totalReceivable,
          totalPaid,
          outstanding: totalReceivable - totalPaid,
        },
      };
    }),
});
