import { z } from 'zod';
import { router, adminProcedure } from '../_core/trpc';
import { TRPCError } from '@trpc/server';
import { getDb } from '../db';

export const profitLossRouter = router({
  getProfitLoss: adminProcedure
    .input(z.object({
      storeId: z.number().optional(),
      year: z.number(),
      month: z.number().min(1).max(12),
    }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: '資料庫連線失敗' });

      const { year, month, storeId } = input;

      // a. 日報加總（totalSales, guestTotal）
      const dailySql = `
        SELECT
          COALESCE(SUM(instoreSales + uberSales + pandaSales + COALESCE(phoneOrderAmount,0) + COALESCE(deliveryOrderAmount,0)), 0) AS totalSales,
          COALESCE(SUM(guestInstore + guestUber + guestPanda), 0) AS guestTotal
        FROM os_daily_reports
        WHERE tenantId = 1
          AND YEAR(reportDate) = ?
          AND MONTH(reportDate) = ?
      `;
      const dailyParams: (number | string)[] = [year, month];
      const [dailyRows] = await (db as any).$client.execute(dailySql, dailyParams);
      const daily = (dailyRows as any[])[0] ?? {};
      const totalSales = Number(daily.totalSales ?? 0);
      const guestTotal = Number(daily.guestTotal ?? 0);

      // 每日銷售趨勢（折線圖）
      const [trendRows] = await (db as any).$client.execute(`
        SELECT
          DATE_FORMAT(reportDate, '%m/%d') AS day,
          SUM(instoreSales + uberSales + pandaSales
              + COALESCE(phoneOrderAmount,0)
              + COALESCE(deliveryOrderAmount,0)) AS sales,
          SUM(guestInstore + guestUber + guestPanda) AS guests
        FROM os_daily_reports
        WHERE tenantId=1 AND YEAR(reportDate)=? AND MONTH(reportDate)=?
        GROUP BY reportDate
        ORDER BY reportDate ASC
      `, [year, month]);
      const dailyTrend = trendRows as any[];

      // 各通路分拆（圓餅圖）
      const [[channelRow]] = await (db as any).$client.execute(`
        SELECT
          COALESCE(SUM(instoreSales),0)        AS instore,
          COALESCE(SUM(uberSales),0)           AS uber,
          COALESCE(SUM(pandaSales),0)          AS panda,
          COALESCE(SUM(phoneOrderAmount),0)    AS phone,
          COALESCE(SUM(deliveryOrderAmount),0) AS delivery
        FROM os_daily_reports
        WHERE tenantId=1 AND YEAR(reportDate)=? AND MONTH(reportDate)=?
      `, [year, month]);
      const channelSales = {
        instore:  Number(channelRow?.instore  ?? 0),
        uber:     Number(channelRow?.uber     ?? 0),
        panda:    Number(channelRow?.panda    ?? 0),
        phone:    Number(channelRow?.phone    ?? 0),
        delivery: Number(channelRow?.delivery ?? 0),
      };

      // b. 月報費用
      const monthlySql = `
        SELECT
          COALESCE(SUM(electricityFee), 0)  AS electricityFee,
          COALESCE(SUM(waterFee), 0)        AS waterFee,
          COALESCE(SUM(staffSalaryCost), 0) AS salaryTotal,
          GROUP_CONCAT(performanceReview SEPARATOR '\n') AS performanceReview,
          GROUP_CONCAT(monthlyPlan SEPARATOR '\n')       AS monthlyPlan
        FROM os_monthly_reports
        WHERE tenantId = 1 AND year = ? AND month = ?
      `;
      const monthlyParams: (number | string)[] = [year, month];
      const [monthlyRows] = await (db as any).$client.execute(monthlySql, monthlyParams);
      const monthly = (monthlyRows as any[])[0] ?? {};
      const electricityFee = Number(monthly.electricityFee ?? 0);
      const waterFee = Number(monthly.waterFee ?? 0);
      const salaryTotal = Number(monthly.salaryTotal ?? 0);
      const performanceReview: string = monthly.performanceReview ?? '';
      const monthlyPlan: string = monthly.monthlyPlan ?? '';

      // c. 退佣收入
      const monthStr = `${year}-${String(month).padStart(2, '0')}`;
      const rebateSql = `
        SELECT COALESCE(SUM(netRebate), 0) AS rebateIncome
        FROM os_rebates
        WHERE tenantId = 1
          AND month = ?
          AND status IN ('received', 'offset', 'pending')
      `;
      const [rebateRows] = await (db as any).$client.execute(rebateSql, [monthStr]);
      const rebateIncome = Number((rebateRows as any[])[0]?.rebateIncome ?? 0);

      // d. 本月出貨帳款應收
      const arSql = `
        SELECT COALESCE(SUM(amount), 0) AS arIncome
        FROM os_franchisee_payments
        WHERE tenantId=1
        AND direction='receivable'
        AND isAutoGenerated=1
        AND YEAR(paymentDate)=?
        AND MONTH(paymentDate)=?`;
      const [[arRow]] = await (db as any).$client.execute(arSql, [year, month]);
      const arIncome = Number((arRow as any)?.arIncome) || 0;

      // e. 食材成本：優先使用 os_payables 真實採購金額
      const [[costRow]] = await (db as any).$client.execute(
        `SELECT COALESCE(SUM(COALESCE(netPayable, totalAmount)), 0) AS procurementCost
         FROM os_payables
         WHERE tenantId=1 AND month=?`,
        [monthStr]
      );
      const procurementCost = Number((costRow as any)?.procurementCost) || 0;
      const foodCost = procurementCost > 0
        ? procurementCost
        : Math.round(totalSales * 0.35);
      const isCostEstimated = procurementCost === 0;

      // f. 損益計算
      const grossProfit = totalSales - foodCost;
      const operatingProfit = grossProfit - electricityFee - waterFee - salaryTotal + rebateIncome + arIncome;
      const profitRate = totalSales > 0 ? operatingProfit / totalSales : 0;
      const avgTicket = guestTotal > 0 ? Math.round(totalSales / guestTotal) : 0;

      return {
        year,
        month,
        storeId: storeId ?? null,
        // 營收
        totalSales,
        guestTotal,
        avgTicket,
        // 成本
        foodCost,
        electricityFee,
        waterFee,
        salaryTotal,
        // 退佣
        rebateIncome,
        // 出貨應收
        arIncome,
        // 損益
        grossProfit,
        operatingProfit,
        profitRate,
        // 採購成本
        procurementCost,
        isCostEstimated,
        // 趨勢與通路
        dailyTrend,
        channelSales,
        // 備註
        performanceReview,
        monthlyPlan,
      };
    }),
});
